2022-09-04 21:00:01,030 : INFO : root : Loading config.
2022-09-04 21:00:01,034 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2022-09-04 21:00:01,035 : WARNING : ConfigProcessor : Config file in cache changed: c:\trashland_2\config\config.yaml
2022-09-04 21:00:01,035 : INFO : ConfigProcessor : Loading config from file c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\mpfconfig.yaml.
2022-09-04 21:00:01,108 : INFO : ConfigProcessor : Loading config: c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\mpfconfig.yaml
2022-09-04 21:00:01,109 : INFO : ConfigProcessor : Loading config from file c:\trashland_2\config\config.yaml.
2022-09-04 21:00:01,205 : INFO : ConfigProcessor : Loading config: c:\trashland_2\config\config.yaml
2022-09-04 21:00:01,208 : INFO : ConfigProcessor : Config file cache created: C:\Users\Tanner\AppData\Local\Temp\a6762098cb994b55cb03a478b26022ee.mpf_cache
2022-09-04 21:00:01,274 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\ec172e3d2b0d14c1982139d23248bb88.mpf_cache
2022-09-04 21:00:01,275 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\c215df352878fee5d54f1a5ec5b16e7c.mpf_cache
2022-09-04 21:00:01,275 : INFO : Machine : Mission Pinball Framework Core Engine v0.55.0
2022-09-04 21:00:01,276 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2022-09-04-21-00-01-mpf-DESKTOP-7HNFDQ5.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2022-09-04 21:00:01,276 : INFO : Machine : MPF path: c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf
2022-09-04 21:00:01,276 : INFO : Machine : Machine path: c:\trashland_2
2022-09-04 21:00:01,276 : INFO : Machine : Platform: win32
2022-09-04 21:00:01,276 : INFO : Machine : Python executable location: c:\users\tanner\appdata\local\programs\python\python37\python.exe
2022-09-04 21:00:01,276 : INFO : Machine : Python version: 3.7.8 (64-bit)
2022-09-04 21:00:01,277 : INFO : Machine : Initialise MPF.
2022-09-04 21:00:01,543 : INFO : FAST : Connecting to com20 at 921600bps
2022-09-04 21:00:01,656 : INFO : FAST : Connected! Processor: NET, Board Type: FP-CPU-002-2, Firmware: 01.00
2022-09-04 21:00:01,656 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'value': '01.00', 'prev_value': None, 'change': True}
2022-09-04 21:00:01,656 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2022-09-04 21:00:06,634 : WARNING : FAST : Reset of NET CPU failed. This might be a firmware bug in your version.
2022-09-04 21:00:07,256 : INFO : FAST : Connecting to com21 at 921600bps
2022-09-04 21:00:07,386 : INFO : FAST : Connected! Processor: RGB, Board Type: FP-CPU-002-2, Firmware: 01.00
2022-09-04 21:00:07,386 : INFO : EventManager : Event: ======'machine_var_fast_rgb_firmware'====== Args={'value': '01.00', 'prev_value': None, 'change': True}
2022-09-04 21:00:07,386 : INFO : EventManager : Event: ======'machine_var_fast_rgb_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2022-09-04 21:00:07,386 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2022-09-04 21:00:07,431 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2022-09-04 21:00:07,431 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.55.0', 'prev_value': None, 'change': True}
2022-09-04 21:00:07,431 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.55.0, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2022-09-04 21:00:07,431 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.7.8', 'prev_value': None, 'change': True}
2022-09-04 21:00:07,432 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19041-SP0', 'prev_value': None, 'change': True}
2022-09-04 21:00:07,432 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2022-09-04 21:00:07,432 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2022-09-04 21:00:07,432 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19041', 'prev_value': None, 'change': True}
2022-09-04 21:00:07,432 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2022-09-04 21:00:07,432 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2022-09-04 21:00:07,440 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...pty config.")>) at c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\events.py:112
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...pty config.")>) at c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\events.py:112>
Traceback (most recent call last):
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\events.py", line 115, in _async_handler_done
    future.result()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\device_manager.py", line 84, in _load_device_modules
    self.create_devices(collection_name, config)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\device_manager.py", line 121, in create_devices
    context=collection_name + "." + device_name)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\logging.py", line 173, in raise_config_error
    from source_exception
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in DeviceManager: Device coils:'c_back_flipper' has an empty config. Context: coils.c_back_flipper Error Code: CFE-DeviceManager-2 (https://docs.missionpinball.org/en/0.55/logs/CFE-DeviceManager-2.html)
2022-09-04 21:00:07,442 : INFO : Machine : Starting the main run loop.
2022-09-04 21:00:07,445 : INFO : Machine : Shutting down...
2022-09-04 21:00:07,445 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2022-09-04 21:00:07,543 : ERROR : FAST : Stop called on serial connection com20
2022-09-04 21:00:07,543 : ERROR : FAST : Stop called on serial connection com21
2022-09-04 21:00:07,780 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\events.py", line 115, in _async_handler_done
    future.result()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\device_manager.py", line 84, in _load_device_modules
    self.create_devices(collection_name, config)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\device_manager.py", line 121, in create_devices
    context=collection_name + "." + device_name)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\logging.py", line 173, in raise_config_error
    from source_exception
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in DeviceManager: Device coils:'c_back_flipper' has an empty config. Context: coils.c_back_flipper Error Code: CFE-DeviceManager-2 (https://docs.missionpinball.org/en/0.55/logs/CFE-DeviceManager-2.html)
2022-09-04 21:00:40,287 : INFO : root : MPF run loop ended.
